language: python
python: '2.7'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- git clone https://github.com/plone/papyrus ../papyrus && cd ../papyrus
- mkdir -p source && ln -s ../../documentation source/documentation
- mkdir -p buildout-cache/downloads
- virtualenv buildout
- buildout/bin/python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg buildout:checkout=documentation sources:documentation="fs
  documentation egg=false"
before_script:
- gem install --version 0.8.9 faraday
- gem install travis-artifacts
script: make html
after_script:
- travis-artifacts upload --path build/html
- travis-artifacts upload --target-path latest --path build/html
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-docs
    template:
    - ! '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
    - ! 'Sphinx: http://plone-documentation.s3-website-us-east-1.amazonaws.com/artifacts/%{build_number}/%{build_number}.1/en/'
env:
  global:
  - ARTIFACTS_S3_BUCKET=plone-documentation
  - secure: prXVT9fqR4dvCZBffLEJspXzakJVJZ7hFKfjFj1R1+xJEX0du5+uhk+ieW+6o3o3Gr+DB006V6IuDNu759giesv98Qs7Py/CIhW5Gowz+8MXZKRR8IA8J57jsozNnQraO2vY/Nzjoqfywc176Z9+Ajn4FuMFwgj+IUoIEZYvF4M=
  - secure: G5IxV7rbrHPQKsUlQdiNle6f7XhZTWZVBiwgLJfRuK/yNP9IWPHkjJF1UrEHasdKHmon6bqKd9KWxuIctSHyS9puzifqaMCbbRpYTW8UjkJx9+UaK9iQF3jV1ulrd2bIz7F/tpz2ZbPYpiv3mKevb6m0HuSZfrnR1r4xdunFKH8=
